import { NextResponse } from "next/server";
import { prisma, type Topic } from "@/lib/db";
import { TOPIC_SEEDS, TOPIC_CATEGORIES, type SeedTopic } from "@/lib/topic-seeds";
import { openAiChat, openAiConfigured } from "@/lib/openai";

const BATCH_SIZE       = 5;
const FROM_CURATED     = 2;            // baseline picks from the vetted list
const FROM_AI          = BATCH_SIZE - FROM_CURATED;
const AI_TIMEOUT_MS    = 15_000;

interface Suggestion {
  title: string;
  description: string;
  category: string;
  difficulty: "intro" | "standard" | "advanced";
  source: "curated" | "ai";
}

/**
 * Hybrid suggester:
 *   - Always returns N=5 ideas.
 *   - The first ~2 come from a curated seed list (filtered to avoid titles
 *     already in the user's bank).
 *   - The remaining ~3 are generated by OpenAI with the bank's existing titles
 *     passed as anti-duplication context.
 *   - If OpenAI isn't configured or errors, the gap is back-filled from the
 *     curated list so the UI never sees an empty response.
 */
export async function POST() {
  const existing = await prisma.topic.findMany();
  const existingNorm = new Set(
    (existing as Topic[]).map((t) => t.title.toLowerCase().trim()),
  );

  const suggestions: Suggestion[] = [];

  // ─── Curated picks ──────────────────────────────────────────────────────
  const curated = shuffle(
    TOPIC_SEEDS.filter((s) => !existingNorm.has(s.title.toLowerCase().trim())),
  ).slice(0, FROM_CURATED);
  for (const s of curated) suggestions.push(seedToSuggestion(s));

  // ─── AI picks ───────────────────────────────────────────────────────────
  if (openAiConfigured()) {
    try {
      const aiSuggestions = await withTimeout(
        generateWithAi(Array.from(existingNorm), FROM_AI),
        AI_TIMEOUT_MS,
      );
      for (const ai of aiSuggestions) {
        if (existingNorm.has(ai.title.toLowerCase().trim())) continue;
        if (suggestions.some((s) => s.title.toLowerCase() === ai.title.toLowerCase())) continue;
        suggestions.push(ai);
        if (suggestions.length >= BATCH_SIZE) break;
      }
    } catch (err) {
      // Swallow — we'll back-fill from curated below. The console log helps
      // ops folks debug a misconfigured key without surfacing it to the UI.
      // eslint-disable-next-line no-console
      console.warn("[topics/suggest] AI step failed:", err);
    }
  }

  // ─── Back-fill from curated if we came up short ─────────────────────────
  if (suggestions.length < BATCH_SIZE) {
    const usedTitles = new Set(suggestions.map((s) => s.title.toLowerCase()));
    const extras = shuffle(
      TOPIC_SEEDS.filter(
        (s) =>
          !existingNorm.has(s.title.toLowerCase().trim()) &&
          !usedTitles.has(s.title.toLowerCase()),
      ),
    );
    for (const s of extras) {
      suggestions.push(seedToSuggestion(s));
      if (suggestions.length >= BATCH_SIZE) break;
    }
  }

  return NextResponse.json({
    suggestions: suggestions.slice(0, BATCH_SIZE),
    aiEnabled: openAiConfigured(),
  });
}

// ─── helpers ────────────────────────────────────────────────────────────────

function seedToSuggestion(s: SeedTopic): Suggestion {
  return {
    title: s.title,
    description: s.description,
    category: s.category,
    difficulty: s.difficulty,
    source: "curated",
  };
}

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function withTimeout<T>(p: Promise<T>, ms: number): Promise<T> {
  return new Promise((resolve, reject) => {
    const t = setTimeout(() => reject(new Error(`Timed out after ${ms}ms`)), ms);
    p.then((v) => { clearTimeout(t); resolve(v); },
           (e) => { clearTimeout(t); reject(e); });
  });
}

async function generateWithAi(existingTitles: string[], count: number): Promise<Suggestion[]> {
  const systemPrompt =
    "You are an experienced Model UN coach helping a high-school MUN club brainstorm fresh debate topics. " +
    "Topics should be currently relevant (the user's school year is the present), substantively debatable at " +
    "the UN level, and varied across categories. Return strictly valid JSON only.";

  // Cap how many existing titles we send. The model only needs enough context
  // to avoid duplicating recent ones; sending the whole bank wastes tokens.
  const recent = existingTitles.slice(0, 40);
  const categories = TOPIC_CATEGORIES.join(", ");

  const userPrompt = [
    `Generate ${count} fresh MUN debate topics.`,
    "",
    "Return JSON shaped exactly as:",
    `{ "topics": [{ "title": string (≤110 chars), "description": string (one sentence framing the debate), "category": string (one of: ${categories}), "difficulty": "intro" | "standard" | "advanced" }] }`,
    "",
    recent.length
      ? `Avoid duplicating these existing topic titles:\n- ${recent.join("\n- ")}`
      : "There are no existing topics yet.",
    "",
    "Mix categories and difficulty levels. Favor topics that connect to events from the past 12 months when possible.",
  ].join("\n");

  const raw = await openAiChat({
    systemPrompt,
    userPrompt,
    jsonMode: true,
    temperature: 1.0,
  });

  let parsed: { topics?: Array<Record<string, unknown>> };
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error(`Could not parse AI JSON: ${raw.slice(0, 200)}`);
  }

  if (!Array.isArray(parsed.topics)) return [];

  return parsed.topics
    .map((t): Suggestion | null => {
      const title = typeof t.title === "string" ? t.title.trim().slice(0, 280) : "";
      const description = typeof t.description === "string" ? t.description.trim().slice(0, 600) : "";
      const category = typeof t.category === "string" ? t.category.trim() : "";
      const difficulty = (["intro", "standard", "advanced"] as const).includes(
        t.difficulty as "intro" | "standard" | "advanced",
      ) ? (t.difficulty as "intro" | "standard" | "advanced") : "standard";
      if (!title) return null;
      return { title, description, category, difficulty, source: "ai" };
    })
    .filter((s): s is Suggestion => s !== null);
}
